include rh-virtio.mak

CONFIG_ARM_GIC_KVM=y
CONFIG_ARM_SMMUV3=y
CONFIG_ARM_V7M=y
CONFIG_ARM_VIRT=y
CONFIG_EDID=y
CONFIG_PCIE_PORT=y
CONFIG_PCI_DEVICES=y
CONFIG_PCI_TESTDEV=y
CONFIG_PFLASH_CFI01=y
CONFIG_SCSI=y
CONFIG_SEMIHOSTING=y
CONFIG_USB=y
CONFIG_USB_XHCI=y
CONFIG_VFIO=y
CONFIG_VFIO_PCI=y
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_XIO3130=y
